# Generated by Django 5.0.6 on 2024-05-15 09:26

import conversation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание линии связи')),
            ],
            options={
                'verbose_name': 'Линия связи',
                'verbose_name_plural': 'Линии связи',
            },
        ),
        migrations.CreateModel(
            name='ReferenceDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст эталонного диалога')),
            ],
            options={
                'verbose_name': 'Эталонный диалог',
                'verbose_name_plural': 'Эталонные диалоги',
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('audio_text', models.TextField(blank=True, null=True, verbose_name='Распознанный текст из аудио')),
                ('date', models.DateField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='negotiation_audio/', validators=[conversation.models.validate_audio_file_extension], verbose_name='Аудиофайл диалога')),
                ('percentage_compliance', models.FloatField(blank=True, null=True, verbose_name='Процент соответвия регламенту')),
                ('regulations_complies', models.BooleanField(default=False, verbose_name='Соответсвует ли регламенту')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.line')),
                ('reference_dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.referencedialog')),
            ],
            options={
                'verbose_name': 'Служебные переговоры',
                'verbose_name_plural': 'Служебные переговоры',
            },
        ),
    ]
