# Generated by Django 5.0.6 on 2024-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модели'),
        ),
    ]
